### ISSUE TITLE
Validation error in input_data when using pandapower basic standard types

### ISSUE THREAD

**Issue by marhofmann** [PowerGridModel/power-grid-model-io#267]
Hi,
I wanted to try power-grid-model by converting an existing pandapower model. I received a validation error while checking the input data with `assert_valid_input_data`:
```
power_grid_model.validation.assertions.ValidationException: There is a validation error in input_data:
	Field 'i0' is not greater than (or equal to) p0/sn for 59 ComponentsTypes.transformers.
```

The transformer type of the transformers which caused this error is from the standard type library of pandapower: `0.63 MVA 20/0.4 kV`. I assume, that this error is raised due to rounding.
From the pandapower standard type library:
`sn_mva = 0.63` and `pfe_kw = 1.65` while `i0_percent = 0.2619`
When i calculate `i0_percent` from the other parameters `1.65 * 1e3 / (0.63 * 1e6) * 1e2` i get `0.2619047619047619`

Maybe the validation function can ignore a certain violation by rounding the values for checking or applying a certain tolerance. I have overwritten the value for 'i0_percent' in the pandapower `trafo` table with the calculated value before conversion as a workaround. 

Thank you for your work! I enjoy using power-grid-model! :)

**Comment by mgovers** [comment]
Hi @marhofmann ,

Thank you for your elaborate feedback! It's great to hear that you enjoy using power-grid-model and that you're willing to spend your time and effort to help us improve.

At first sight, it indeed seems related to rounding errors, possibly related to the 4-digit precision. However, we will investigate a little bit more before we draw any conclusions and come up with a mitigation strategy.

**Comment by nitbharambe** [comment]
Hi @marhofmann ,
Nice that you enjoy using PGM! And that's great analysis with a good workaround.
Unfortunately we cannot change the validation function to keep it generic. When rounding is allowed, results would deviate very slightly from what is theoretically accurate. 

Maybe user might not experience an error by PGM and get a legible result when input is not validated. That is because inside the PGM core, there is indeed a workaround by setting it `=p0/sn` instead of throwing an error for a minor inaccuracy like rounding.  The purpose of validation functions however is to guarantee 100% accurate calculation.

I propose we add this to the documentation referring to this predefined transformer type with the workaround you specified.   This would be under a new title of `Common known issues` at https://github.com/PowerGridModel/power-grid-model-io/blob/main/docs/converters/pandapower_converter.md

**Comment by mgovers** [comment]
@nitbharambe I agree that it should not be part of the data validator. Is it something we can add to the pandapower converter instead? Or is that too risky as well?

**Comment by marhofmann** [comment]
Hi,
@nitbharambe, thank you for explaining! 
I agree with @mgovers, that implementing it inside the converter would increase useability. How about setting the calculated value for the power-grid-model version of the distribution grid model and printing a user warning to inform the user that it was changed during conversion? The simulation could be carried out and the user could decide if the calculated value is acceptable/close enough to the "original" value from the pandapower model.

**Comment by nitbharambe** [comment]
The converter itself does not validate the data anywhere. Hence the converter has no idea if a certain rounding is required or not, or to which side rounding must be done. And how much rounding to be done.

- The validation currently happens either using `assert_valid_input_data` by the user after converting with pgm-io directly. 
- Or it happens at the pandapower side (via pgm-io). Modifying the behavior at pandapower side on `runpp_pgm` might not be the best scenario. It might be in form of an additional default argument (or **kwargs) in the function and it would indeed involve pandapower's team in the decision. This request doesn't seem like a strong proposal when we can chose to set `validate_input=False`

If disabling validation is not an option, it can be manually overridden by using `validate_input_data` function instead of `assert_valid_input_data`. Then any errors matching the above error message can be ignored without hard crash. This still seems like work on the user side though and might not be what we are looking for. It can be this way:
```
errors = validate_input_data()
if errors is not None or not all(error.field == "i0" for error in errors):
   ... Other validation problem to be handled...
... "i0" is ignored  from errors ...
```

**Comment by nitbharambe** [comment]
Checking if its possible @mgovers  @marhofmann

**Comment by marhofmann** [comment]
I did not clarify that I converted the model myself ([as described here](https://power-grid-model-io.readthedocs.io/en/stable/examples/pandapower_example.html)). I did not use “runpp_pgm” from pandapower, because I wanted to try the batch calculation of power-grid-model, which is currently not accessible via pandapower, as far as I have seen.

**Comment by mgovers** [comment]
@marhofmann As you can see, @nitbharambe has enforced the inequality `i0 >= p0/sn` in the actual pandapower conversion functionality. I hope this has resolved your issue. If not, feel free to re-open and provide more input.

**Comment by nitbharambe** [comment]
I see its merged! [v1.2.97](https://github.com/PowerGridModel/power-grid-model-io/releases/tag/v1.2.97)
Good suggestion @marhofmann . It shall improve usability for other pandapower users!

**Comment by marhofmann** [comment]
Thank you very much @mgovers & @nitbharambe!
I tested it without my workaround and I received this warning: 
```
2024-08-22 11:24:03 [warning  ] Minimum value of i0_percent is clipped to p0/sn
```
and the simulation was carried out without an error. That's great!

**Comment by mgovers** [comment]
That's great to hear! Thank you for the feedback!
